name: 'PHPStan | L8'
on: [push]
jobs:
  phpstan:
    name: 'PHPStan | L8'
    runs-on: ubuntu-latest
    steps:
      - name: 'Install system dependencies'
        run: 'sudo apt install -y composer php'
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Install Composer dependencies'
        run: 'composer install --no-interaction'
      - name: 'Run PHPStan tests'
        run: './vendor/bin/phpstan analyze --level=8 src tests'
