name: 'Testing'
on: [push]
jobs:
  testing:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - name: 'Add ppa:ondrej/php repository'
        run: 'sudo apt-add-repository -y ppa:ondrej/php'
      - name: 'Install system dependencies'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: 'sudo apt-get -qq install composer php7.4-cli php7.4-xdebug'
      - name: 'Enable Xdebug extension for PHP'
        run: 'sudo phpenmod xdebug'
      - name: 'Print enabled PHP extensions'
        run: 'php -m'
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Install Composer dependencies'
        run: 'composer install --no-interaction --no-progress'
      - name: 'Run PHPUnit tests'
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          XDEBUG_MODE: coverage
        with:
          coverageCommand: './vendor/bin/phpunit'
          coverageLocations: clover.xml:clover
      - name: 'Run PHPStan tests'
        run: './vendor/bin/phpstan analyze --no-progress --level=8 src tests'
