name: 'Testing'
on: [push]
jobs:
  testing:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Set up the test environment'
        run: ./scripts/setup-test-environment.sh
      - name: 'Run PHPUnit tests'
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: ./vendor/bin/phpunit --coverage-clover=clover.xml
          coverageLocations: clover.xml:clover
      - name: 'Run PHPStan tests'
        run: ./vendor/bin/phpstan analyze --no-progress --level=8 src tests
