name: 'Testing'
on: [push]
jobs:
  testing:
    name: 'Testing'
    runs-on: ubuntu-latest
    env:
      XDEBUG_MODE: coverage
    steps:
      - name: 'Install system dependencies'
        run: 'sudo apt install -y composer php php-xdebug'
      - name: 'Enable Xdebug extension for PHP'
        run: 'sudo phpenmod xdebug'
      - name: 'Print enabled PHP extensions'
        run: 'php -m'
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Install Composer dependencies'
        run: 'composer install --no-interaction --no-progress'
      - name: 'Run PHPUnit tests'
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: './vendor/bin/phpunit'
          coverageLocations: clover.xml:clover
      - name: 'Run PHPStan tests'
        run: './vendor/bin/phpstan analyze --level=8 src tests'
