name: 'PHPUnit'
on: [push]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: 'Install system dependencies'
        run: 'sudo apt install -y composer php php-xdebug'
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Install Composer dependencies'
        run: 'composer install --no-interaction'
      - name: 'Run PHPUnit tests'
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: './vendor/bin/phpunit'
          coverageLocations: clover.xml:clover
